@startuml WatchBuddy
!theme cb_seq_YlOrBr_9 from https://raw.githubusercontent.com/mweagle/C4-PlantUML-Themes/main/palettes
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
' LAYOUT_LEFT_RIGHT()

title WatchBuddy

/' People '/
' Person(User, "User")
' Person(Admin, "Admin")

' /' System boundary '/
System(WB, "WatchBuddy"){
  
  Container(Web, "Web Application", "Vite + Vue + TypeScript + Tailwind"){
    ' Component(NavBar, "Navigation Bar", "Vue")
    Component(WatchParty, "Watch Party", "Vue", "Lobby, chat, syncs playback, split between public and private rooms generic questions for public rooms, ability to fast forward timer for private rooms")
    Component(Recommender, "Recommender", "Vue", "Recommendation based on Mood/Genre")
    Component(Reviews, "Reviews and Rating", "Vue", "Write reviews, vote helpfulness")
    Component(Profile, "Profile & Friends", "Vue", "Friends, history, badges")
    Component(Settings, "Settings", "Vue", "Change mood/genre settings, user details")
    Component(Supabase, "Supabase Client", "Typescript", "Connects to Supabase client")
    Component(Login, "Login", "Supabase Auth", "Login to site")
  }

  ContainerDb(STORE, "Database + Hosting", "Supabase"){
    ' Movies Info
    ' TV Info
    ' User Info
    ' User Lists

    ' "Tables & RLS\nusers, profiles, preferences, friends,\nmedia, genres, media_genres, moods, media_moods,\nwatch_history, watch_party, watch_party_member, messages,\nreviews, review_votes, ratings_aggregate,\nbadges, user_badges, recommendations, similar_users" as Schema
    ' component "Views & Materialized Views\nAdjusted ratings, rec materializations" as Views
    ' component "Triggers & RPC (PL/pgSQL)\nConsistency, counters, safe RPC" as Triggers
  }

  Container(AUTH, "Supabase Auth", "JWT sessions")

  Container(EDGE, "Supabase Edge Functions", "Typescript", "description"){
    Component(TMDBSyncFn, "TMDB Sync", "Typescript", "Fetch, diff, update new movies/trending from TMDB once per day")
    Component(RecFn, "Recommendation Engine", "Typescript", "CF + mood/genre + roulette")
    Component(BadgesFn, "Badges & Gamification", "Typescript", "TBC: Award based on activity")
    Component(AlertsFn, "Quiz/Trivia Alerts", "Typescript", "TBC: Half-time & facts notifier")
  }

  Container_Ext(TMDB, "TMDB API", "TMDB API")
}

' /' Web components wiring '/
BiRel_R(Web, EDGE, "")
BiRel_D(Login, AUTH, "")

BiRel_R(EDGE, STORE, "")
BiRel_R(STORE, AUTH, "")
BiRel_D(TMDBSyncFn, TMDB, "Fetch Updates", "REST")

@enduml
