/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./../components/BaseFooter.vue')['default']
    BaseNavBar: typeof import('./../components/navbar/BaseNavBar.vue')['default']
    BaseSearchBar: typeof import('./../components/BaseSearchBar.vue')['default']
    BaseUserButton: typeof import('./../components/navbar/BaseUserButton.vue')['default']
    CreateParty: typeof import('./../components/watchparty/CreateParty.vue')['default']
    DbTemplate: typeof import('./../components/database/DbTemplate.vue')['default']
    Header: typeof import('./../components/watchparty/Header.vue')['default']
    HomeMood: typeof import('./../components/HomeMood.vue')['default']
    Leaderboard: typeof import('./../components/Leaderboard.vue')['default']
    MovieCard: typeof import('./../components/MovieCard.vue')['default']
    MovieReviews: typeof import('./../components/reviews/MovieReviews.vue')['default']
    NavLinks: typeof import('./../components/navbar/NavLinks.vue')['default']
    RoomCard: typeof import('./../components/watchparty/RoomCard.vue')['default']
    RoomRow: typeof import('./../components/watchparty/RoomRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Trending: typeof import('./../components/Trending.vue')['default']
    UserManagement: typeof import('./../components/navbar/UserManagement.vue')['default']
    WatchPartyList: typeof import('./../components/watchparty/WatchPartyList.vue')['default']
  }
}
