/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./../components/BaseFooter.vue')['default']
    BaseNavBar: typeof import('./../components/BaseNavBar.vue')['default']
    BaseSearchBar: typeof import('./../components/BaseSearchBar.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    CreateParty: typeof import('./../components/WatchParty/CreateParty.vue')['default']
    DbTemplate: typeof import('./../components/DbTemplate.vue')['default']
    HomeMood: typeof import('./../components/HomeMood.vue')['default']
    Image: typeof import('primevue/image')['default']
    Leaderboard: typeof import('./../components/Leaderboard.vue')['default']
    MovieCard: typeof import('./../components/MovieCard.vue')['default']
    PartyRoomCard: typeof import('./../components/WatchParty/PartyRoomCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestNavBar: typeof import('./../components/TestNavBar.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    Trending: typeof import('./../components/Trending.vue')['default']
    UserManagement: typeof import('./../components/UserManagement.vue')['default']
    WatchPartyList: typeof import('./../components/WatchParty/WatchPartyList.vue')['default']
  }
}
