name: Manual Deployment Cleanup
on:
  workflow_dispatch:
    inputs:
        environment:
          required: true
          type: string
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ inputs.environment}}
          onlyRemoveDeployments: true{{ inputs.name }}"
